import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Building2, Check, Factory, Network, Store, Users } from 'lucide-react';
import { SiteFooter } from '../../components/site-footer';
import { SiteHeader } from '../../components/site-header';

export const metadata: Metadata = { title: 'Lösungen | VYSN', description: 'VYSN One für kleine Unternehmen und VYSN Pro für anspruchsvolle Organisationen.' };

export default function SolutionsPage(){return <main><SiteHeader />
  <section className="page-hero shell"><span className="section-kicker">LÖSUNGEN</span><h1>Passend zur Größe.<br/><span>Bereit für den nächsten Schritt.</span></h1><p>VYSN beginnt dort, wo dein Unternehmen heute steht – und wächst mit Prozessen, Teams und Standorten weiter.</p></section>
  <section className="audience-section shell"><article className="audience-card"><div className="audience-icon"><Store/></div><span>VYSN ONE</span><h2>Für kleine Unternehmen &amp; Teams.</h2><p>Struktur für das Tagesgeschäft, ohne lange Einführung. Ideal für Dienstleister, Handwerk, Agenturen und wachsende Betriebe.</p><ul>{['Direkt einsatzbereit','Zentrale Kunden- und Auftragsverwaltung','Angebote, Rechnungen und Finanzen','Bis zu 5 Nutzer'].map(x=><li key={x}><Check/>{x}</li>)}</ul><Link className="button button-primary" href="/preise">One kennenlernen <ArrowRight/></Link></article>
  <article className="audience-card dark" id="pro"><div className="audience-icon"><Building2/></div><span>VYSN PRO</span><h2>Für größere Firmen &amp; individuelle Abläufe.</h2><p>Eine Unternehmensplattform, die an Organisation, Rollen und vorhandene Systeme angepasst wird.</p><ul>{['Individuelle Module & Workflows','Mehrere Firmen und Standorte','Schnittstellen zu Drittsystemen','Persönliche Einführung und Betreuung'].map(x=><li key={x}><Check/>{x}</li>)}</ul><a className="button button-light" href="mailto:hallo@vysn.de?subject=VYSN%20Pro%20Beratung">Pro-Beratung anfragen <ArrowRight/></a></article></section>
  <section className="usecase-section"><div className="shell"><div className="section-heading"><div><span className="section-kicker">EINSATZBEREICHE</span><h2>VYSN passt sich der Arbeit an.</h2></div><p>Von klaren Standardabläufen bis zur komplexen, standortübergreifenden Organisation.</p></div><div className="usecase-grid">{[[Users,'Dienstleistung','Kunden, Projekte und Abrechnung in einem durchgängigen Ablauf.'],[Factory,'Handwerk & Produktion','Aufträge, Material, Termine und Kosten zuverlässig zusammenführen.'],[Network,'Unternehmensgruppen','Mehrere Teams, Gesellschaften und Berechtigungen zentral steuern.']].map(([Icon,title,text])=><article key={String(title)}><Icon/><h3>{String(title)}</h3><p>{String(text)}</p></article>)}</div></div></section>
  <section className="process-section shell"><div className="section-heading centered"><span className="section-kicker">DER PRO-WEG</span><h2>Von komplex zu klar.</h2></div><div className="process-grid">{[['01','Verstehen','Wir analysieren Abläufe, Rollen und Ziele.'],['02','Gestalten','Wir konfigurieren Module, Rechte und Schnittstellen.'],['03','Einführen','Wir begleiten Daten, Team und Go-live.'],['04','Weiterdenken','VYSN entwickelt sich mit Ihrem Unternehmen weiter.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <SiteFooter /></main>}
