import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, BriefcaseBusiness, Check, Hammer, Palette, Wrench, type LucideIcon } from 'lucide-react';
import { SiteFooter } from '../../components/site-footer';
import { SiteHeader } from '../../components/site-header';

export const metadata: Metadata = { title:'Lösungen | VYSN One', description:'VYSN One für Handwerk, Dienstleistung, Agenturen und wachsende kleine Unternehmen.' };
const audiences:Array<[LucideIcon,string,string,string[]]>=[[Hammer,'Handwerk & Ausbau','Aufträge, Materialbestände, Angebote, Rechnungen und Projektfortschritt in einem System.',['Baustellen und Termine koordinieren','Materialengpässe früh erkennen','Leistungen sauber abrechnen']],[BriefcaseBusiness,'Dienstleistungsbetriebe','Vom Erstkontakt über das Angebot bis zur Rechnung bleibt jeder Kundenauftrag nachvollziehbar.',['Kundenhistorie zentral pflegen','Aufgaben verbindlich zuordnen','Offene Rechnungen im Blick behalten']],[Palette,'Agenturen & Kreativteams','Projekte, Budgets, Kundenkommunikation und Abrechnung werden für das ganze Team transparent.',['Projektstände schneller erfassen','Angebote strukturiert erstellen','Umsatz und Auslastung verstehen']],[Wrench,'Service & Wartung','Wiederkehrende Einsätze, Kundendaten und Abrechnungen lassen sich klar und zuverlässig organisieren.',['Einsätze dokumentieren','Historie pro Kunde verfügbar','Folgeaufgaben nicht vergessen']]];

export default function SolutionsPage(){return <main><SiteHeader/>
  <section className="page-hero shell"><span className="section-kicker">LÖSUNGEN</span><h1>Für kleine Unternehmen,<br/><span>die Großes vorhaben.</span></h1><p>VYSN One eignet sich für Betriebe, in denen Kunden, Aufträge, Material und Rechnungen täglich zusammengehören – und Informationen trotzdem oft verteilt sind.</p><Link className="button button-primary" href="/kontakt">Passung prüfen <ArrowRight/></Link></section>
  <section className="solution-grid shell">{audiences.map(([Icon,title,text,points])=><article key={title}><div className="solution-icon"><Icon/></div><h2>{title}</h2><p>{text}</p><ul>{points.map(x=><li key={x}><Check/>{x}</li>)}</ul><Link href="/kontakt">Lösung besprechen <ArrowRight/></Link></article>)}</section>
  <section className="usecase-section"><div className="shell"><div className="section-heading"><div><span className="section-kicker">TYPISCHE AUSGANGSLAGE</span><h2>Kommt dir das bekannt vor?</h2></div><p>VYSN One setzt dort an, wo tägliche Reibung Zeit kostet und Informationen verloren gehen.</p></div><div className="pain-grid">{[['Zu viele Listen','Aufträge stehen in Excel, Termine im Kalender und Zahlen in einer anderen Software.'],['Unklare Zuständigkeiten','Aufgaben werden mündlich verteilt und der aktuelle Stand muss nachgefragt werden.'],['Späte Übersicht','Offene Rechnungen, Materialengpässe oder sinkende Auftragswerte werden zu spät sichtbar.'],['Doppelte Arbeit','Kunden- und Projektdaten werden für Angebot, Auftrag und Rechnung mehrfach eingetragen.']].map(([t,d],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="process-section shell"><div className="section-heading centered"><span className="section-kicker">DER START MIT VYSN ONE</span><h2>Strukturiert eingeführt.</h2><p className="center-copy">Ein klarer Start sorgt dafür, dass VYSN One vom ersten Tag an zum Betrieb passt.</p></div><div className="process-grid three">{[['01','Kennenlernen','Wir klären Team, Abläufe und Ziele in einem kurzen Gespräch.'],['02','Einrichten','Firmendaten, Nutzer und Grundeinstellungen werden vorbereitet.'],['03','Loslegen','Das Team erhält einen verständlichen Einstieg und beginnt mit echten Vorgängen.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="home-cta shell"><div><span className="section-kicker light">PASST VYSN ONE ZU DEINEM BETRIEB?</span><h2>Finden wir es in 30 Minuten heraus.</h2></div><Link className="button button-light" href="/kontakt">Unverbindlich sprechen <ArrowRight/></Link></section><SiteFooter/></main>}
