import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, BarChart3, Boxes, BriefcaseBusiness, Check, FileCheck2, ReceiptText, Settings2, Users, WalletCards, type LucideIcon } from 'lucide-react';
import { SiteFooter } from '../../components/site-footer';
import { SiteHeader } from '../../components/site-header';

export const metadata: Metadata = { title:'Produkt | VYSN One', description:'Alle Funktionen von VYSN One: Aufträge, Material, Angebote, Rechnungen, Finanzen, Kunden und Berichte.' };
const modules:Array<[LucideIcon,string,string,string]>=[
  [BriefcaseBusiness,'Aufträge','Vom ersten Termin bis zum Abschluss','Status, Termine, Verantwortliche, Notizen und Dokumente bleiben direkt am Auftrag.'],
  [Boxes,'Materialbestand','Bestände sehen, Engpässe vermeiden','Artikel, Mengen, Mindestbestände und Bewegungen werden zentral erfasst.'],
  [FileCheck2,'Angebote','Schneller professionell anbieten','Angebote aus Kundendaten und Positionen erstellen, versenden und nachverfolgen.'],
  [ReceiptText,'Rechnungen','Sauber abrechnen, Zahlungen verfolgen','Rechnungen aus Aufträgen übernehmen und offene, bezahlte oder überfällige Beträge erkennen.'],
  [WalletCards,'Einnahmen & Ausgaben','Finanzen ohne Tabellen-Puzzle','Geschäftsvorgänge kategorisieren und die Entwicklung des Betriebs laufend verstehen.'],
  [Users,'Kunden','Die ganze Kundenbeziehung an einem Ort','Kontakte, Historie, Aufträge, Angebote und Rechnungen ergeben eine vollständige Kundenakte.'],
  [BarChart3,'Berichte','Kennzahlen, die Entscheidungen erleichtern','Umsatz, Auftragslage, offene Posten und Materialwert verständlich auswerten.'],
  [Settings2,'Einstellungen','VYSN One passend einrichten','Firmendaten, Nummernkreise, Nutzer, Rollen und Dokumentvorgaben zentral verwalten.'],
];

export default function ProductPage(){return <main><SiteHeader/>
  <section className="page-hero shell"><span className="section-kicker">DAS PRODUKT</span><h1>Dein Betrieb.<br/><span>Übersichtlich organisiert.</span></h1><p>VYSN One verbindet alle kaufmännischen und operativen Kernbereiche kleiner Unternehmen – ohne komplizierte Einführung und ohne tägliches Wechseln zwischen Einzellösungen.</p><div className="hero-actions"><Link className="button button-primary" href="/kontakt">Demo anfragen <ArrowRight/></Link><Link className="button button-ghost" href="/preise">Preise ansehen</Link></div></section>
  <section className="flow-strip"><div className="shell flow-row"><span>Kunde</span><ArrowRight/><span>Angebot</span><ArrowRight/><span>Auftrag</span><ArrowRight/><span>Material</span><ArrowRight/><span>Rechnung</span><ArrowRight/><span>Auswertung</span></div></section>
  <section className="detail-section shell"><div className="section-heading"><div><span className="section-kicker">FUNKTIONSBEREICHE</span><h2>Alles, was dein Tagesgeschäft braucht.</h2></div><p>Jeder Bereich ist klar aufgebaut. Weil alle Daten zusammengehören, musst du Informationen nur einmal pflegen.</p></div><div className="product-module-grid">{modules.map(([Icon,title,subtitle,text],i)=><article id={title.toLowerCase().replace(/ /g,'-')} key={title}><div className={`detail-icon tone-${(i%4)+1}`}><Icon/></div><span>VYSN ONE</span><h3>{title}</h3><strong>{subtitle}</strong><p>{text}</p><a href="/kontakt">Im Demo-Termin ansehen <ArrowRight/></a></article>)}</div></section>
  <section className="workflow-section"><div className="shell workflow-inner"><div><span className="section-kicker light">EIN DURCHGÄNGIGER ABLAUF</span><h2>Aus Daten wird ein funktionierender Prozess.</h2><p>Ein bestätigtes Angebot wird zum Auftrag. Positionen und Kundendaten bleiben erhalten. Aus dem abgeschlossenen Auftrag entsteht die Rechnung. Das Dashboard aktualisiert sich automatisch.</p><ul>{['Weniger doppelte Eingaben','Weniger Übertragungsfehler','Klare Verantwortlichkeiten','Aktuelle Zahlen ohne Nacharbeit'].map(x=><li key={x}><Check/>{x}</li>)}</ul></div><div className="workflow-demo"><div><small>01</small><strong>Angebot bestätigt</strong><span>ANG-2026-028</span></div><ArrowRight/><div><small>02</small><strong>Auftrag angelegt</strong><span>BA-2026-018</span></div><ArrowRight/><div><small>03</small><strong>Rechnung erstellt</strong><span>RE-2026-045</span></div></div></div></section>
  <section className="detail-section shell"><div className="section-heading centered"><span className="section-kicker">EINFACH IM ALLTAG</span><h2>Für Menschen gebaut, nicht für IT-Abteilungen.</h2></div><div className="benefit-grid">{[['Schnell verständlich','Klare Sprache, vertraute Abläufe und eine ruhige Oberfläche erleichtern den Einstieg.'],['Gemeinsam arbeiten','Aktuelle Informationen stehen dem gesamten Team dort zur Verfügung, wo sie gebraucht werden.'],['Mitwachsende Struktur','Nutzer, Daten und Arbeitsvolumen können wachsen, ohne dass der Betrieb neu organisiert werden muss.']].map(([t,d])=><article key={t}><Check/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  <section className="home-cta shell"><div><span className="section-kicker light">VYSN ONE LIVE ERLEBEN</span><h2>Wir zeigen dir den Ablauf an deinem Beispiel.</h2></div><Link className="button button-light" href="/kontakt">Demo vereinbaren <ArrowRight/></Link></section><SiteFooter/></main>}
