import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Check } from 'lucide-react';
import { SiteFooter } from '../../components/site-footer';
import { SiteHeader } from '../../components/site-header';

export const metadata: Metadata = { title:'Preise | VYSN One', description:'Transparenter Einstieg in VYSN One ab 39 Euro monatlich für kleine Unternehmen.' };
const included=['Dashboard & Unternehmensübersicht','Auftragsverwaltung','Materialbestand','Angebote & Rechnungen','Einnahmen & Ausgaben','Kundenverwaltung','Berichte','Bis zu 5 Nutzer','E-Mail-Support','Regelmäßige Produktupdates'];

export default function PricingPage(){return <main><SiteHeader/>
  <section className="page-hero compact shell"><span className="section-kicker">PREISE</span><h1>Ein System.<br/><span>Ein transparenter Einstieg.</span></h1><p>VYSN One enthält alle zentralen Funktionsbereiche. Du startest ohne versteckte Modulpakete und kannst das System vorab kennenlernen.</p></section>
  <section className="single-price-section shell"><article className="single-price-card"><div className="single-price-copy"><span className="price-label">VYSN ONE</span><h2>Alles für dein Tagesgeschäft.</h2><p>Für kleine Unternehmen und Teams, die Kunden, Aufträge, Material, Dokumente und Finanzen zusammenführen möchten.</p><div className="big-price"><em>ab</em><strong>39 €</strong><small>/ Monat<br/>zzgl. MwSt.</small></div><Link className="button button-primary" href="/kontakt">Kostenlose Demo anfragen <ArrowRight/></Link><small className="price-fineprint">Die konkrete Preisgestaltung richtet sich nach Nutzerzahl und vereinbartem Leistungsumfang.</small></div><div className="single-price-features"><span>IM SYSTEM ENTHALTEN</span>{included.map(x=><div key={x}><Check/>{x}</div>)}</div></article></section>
  <section className="pricing-steps"><div className="shell"><div className="section-heading centered"><span className="section-kicker">SO GEHT ES WEITER</span><h2>Vom Interesse zum produktiven Einsatz.</h2></div><div className="process-grid three">{[['01','Demo','Du siehst VYSN One mit realistischen Abläufen und stellst deine Fragen.'],['02','Angebot','Du erhältst ein klares Angebot passend zur Nutzerzahl und Einführung.'],['03','Start','Wir richten die Basis ein und begleiten dein Team beim Einstieg.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="faq-page shell"><div><span className="section-kicker">HÄUFIGE FRAGEN</span><h2>Klar beantwortet.</h2></div><div>{[['Welche Funktionen sind enthalten?','Die zentralen Bereiche Dashboard, Aufträge, Material, Angebote, Rechnungen, Finanzen, Kunden, Berichte und Einstellungen gehören zu VYSN One.'],['Wie viele Nutzer können starten?','Der Einstieg ist für Teams mit bis zu fünf Nutzern vorgesehen. Weitere Anforderungen klären wir im Gespräch.'],['Gibt es eine Einrichtungsgebühr?','Ob Einrichtungsleistungen notwendig sind, hängt von Datenübernahme und gewünschter Begleitung ab und wird transparent angeboten.'],['Kann ich VYSN One vorher sehen?','Ja. In einer persönlichen Demo zeigen wir dir die Oberfläche und typische Abläufe, bevor du dich entscheidest.'],['Wie erfolgt die Kündigung?','Vertragslaufzeit und Kündigungsbedingungen werden im individuellen Angebot und den geltenden Vertragsunterlagen klar ausgewiesen.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <section className="home-cta shell"><div><span className="section-kicker light">OHNE RISIKO KENNENLERNEN</span><h2>Erst sehen. Dann entscheiden.</h2></div><Link className="button button-light" href="/kontakt">Demo anfragen <ArrowRight/></Link></section><SiteFooter/></main>}
