import type { Metadata } from 'next';
import { ArrowRight, Check, Minus } from 'lucide-react';
import { SiteFooter } from '../../components/site-footer';
import { SiteHeader } from '../../components/site-header';

export const metadata: Metadata = { title: 'Preise | VYSN', description: 'VYSN One ab 39 Euro und VYSN Pro als individuelle Unternehmenslösung.' };
const rows=[['Aufträge, Kunden & Finanzen',true,true],['Angebote & Rechnungen',true,true],['Standard-Dashboard',true,true],['Individuelle Workflows',false,true],['Eigene Module & Integrationen',false,true],['Mehrere Standorte',false,true],['Persönliche Betreuung','E-Mail','Dediziert']];

export default function PricingPage(){return <main><SiteHeader />
  <section className="page-hero compact shell"><span className="section-kicker">PREISE</span><h1>Zwei Versionen.<br/><span>Eine klare Entscheidung.</span></h1><p>Einfach starten mit VYSN One oder VYSN Pro passgenau für Ihre Organisation gestalten.</p></section>
  <section className="pricing-section shell"><div className="pricing-grid"><article className="price-card"><div className="price-top"><span>VYSN ONE</span><small>Für kleine Unternehmen &amp; Teams</small></div><p>Die vollständige Basis für ein professionell organisiertes Tagesgeschäft.</p><div className="big-price"><em>ab</em><strong>39 €</strong><small>/ Monat<br/>zzgl. MwSt.</small></div><a className="button button-primary" href="mailto:hallo@vysn.de?subject=VYSN%20One%20testen">14 Tage kostenlos testen <ArrowRight/></a><ul>{['Auftrags- und Kundenverwaltung','Angebote und Rechnungen','Einnahmen und Ausgaben','Dashboard und Standardberichte','Bis zu 5 Nutzer','E-Mail-Support'].map(x=><li key={x}><Check/>{x}</li>)}</ul></article>
  <article className="price-card dark"><div className="price-badge">INDIVIDUELL KONFIGURIERT</div><div className="price-top"><span>VYSN PRO</span><small>Für größere Firmen &amp; komplexe Prozesse</small></div><p>Eine Plattform, die sich an Ihre Organisation anpasst – nicht umgekehrt.</p><div className="big-price"><strong>Individuell</strong><small>Planung, Einführung<br/>und Betreuung</small></div><a className="button button-light" href="mailto:hallo@vysn.de?subject=VYSN%20Pro%20Beratung">Beratung anfragen <ArrowRight/></a><ul>{['Alle Funktionen aus VYSN One','Individuelle Module und Workflows','Unbegrenzte Nutzer und Standorte','Schnittstellen zu Drittsystemen','SSO, Rollen und Freigaben','Persönlicher Ansprechpartner'].map(x=><li key={x}><Check/>{x}</li>)}</ul></article></div><p className="pricing-note">VYSN One: monatlich kündbar, keine Kreditkarte im Testzeitraum. Pro erhält ein individuelles Angebot.</p></section>
  <section className="compare-section shell"><div className="section-heading"><div><span className="section-kicker">VERGLEICH</span><h2>Was passt zu deinem Unternehmen?</h2></div></div><div className="compare-table"><div className="compare-row compare-head"><b>Funktion</b><strong>VYSN One</strong><strong>VYSN Pro</strong></div>{rows.map(([name,one,pro])=><div className="compare-row" key={String(name)}><span>{name}</span><span>{one===true?<Check/>:one===false?<Minus/>:one}</span><span>{pro===true?<Check/>:pro}</span></div>)}</div></section>
  <section className="faq-page shell"><div><span className="section-kicker">HÄUFIGE FRAGEN</span><h2>Gut zu wissen.</h2></div><div>{[['Kann ich VYSN One kostenlos testen?','Ja. 14 Tage ohne Kreditkarte. Danach entscheidest du, ob du weitermachen möchtest.'],['Kann ich später zu Pro wechseln?','Ja. Bestehende Daten und Abläufe bilden die Grundlage für deine Pro-Lösung.'],['Wie entsteht der Pro-Preis?','Der Preis richtet sich nach Modulen, Integrationen, Nutzern und Einführungsumfang. Du erhältst ein transparentes Angebot.'],['Gibt es eine Einrichtungsgebühr?','Für VYSN One nicht. Bei Pro wird die individuelle Einführung im Angebot ausgewiesen.']].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
  <SiteFooter /></main>}
