'use client';

import { useState } from 'react';
import { BarChart3, Boxes, BriefcaseBusiness, FileCheck2, LayoutDashboard, ReceiptText, Settings, Users, WalletCards } from 'lucide-react';

type ViewId='dashboard'|'auftraege'|'material'|'angebote'|'rechnungen'|'finanzen'|'kunden'|'berichte'|'einstellungen';
const navigation=[
  ['dashboard','Dashboard',LayoutDashboard],['auftraege','Aufträge',BriefcaseBusiness],['material','Materialbestand',Boxes],['angebote','Angebote',FileCheck2],['rechnungen','Rechnungen',ReceiptText],['finanzen','Einnahmen & Ausgaben',WalletCards],['kunden','Kunden',Users],['berichte','Berichte',BarChart3],['einstellungen','Einstellungen',Settings]
] as const;

const data:Record<string,{title:string;kicker:string;copy:string;columns:string[];rows:string[][]}>={
  auftraege:{title:'Aktive Aufträge',kicker:'AUFTRÄGE',copy:'Termine, Fortschritt und Auftragswerte zentral verfolgen.',columns:['Nummer','Projekt','Auftragswert','Status'],rows:[['BA-2026-018','Neubau Einfamilienhaus','18.750 €','65% · In Arbeit'],['BA-2026-017','Sanierung Altbau','12.340 €','40% · In Arbeit'],['BA-2026-016','Anbau Wohnhaus','8.950 €','20% · Geplant'],['BA-2026-015','Dachgeschossausbau','14.500 €','80% · In Arbeit']]},
  material:{title:'Materialbestand',kicker:'LAGER & MATERIAL',copy:'Bestände, Mindestmengen und Lagerwert im Blick behalten.',columns:['Artikel','Bestand','Mindestmenge','Status'],rows:[['Zement 25kg','12 Sack','20 Sack','Nachbestellen'],['Holzlatten 4×6cm','18 Stück','25 Stück','Niedrig'],['Dämmwolle 10cm','5 Rollen','10 Rollen','Niedrig'],['Rigipsplatte 12,5mm','8 Platten','20 Platten','Nachbestellen']]},
  angebote:{title:'Angebote',kicker:'VERKAUF',copy:'Angebote erstellen, nachverfolgen und in Aufträge überführen.',columns:['Nummer','Kunde / Projekt','Betrag','Status'],rows:[['ANG-2026-028','Neubau Müller','18.750 €','In Bearbeitung'],['ANG-2026-027','Sanierung Schule','12.340 €','Versendet'],['ANG-2026-026','Anbau Weber','8.950 €','Entwurf'],['ANG-2026-025','Dachausbau Klein','14.500 €','Angenommen']]},
  rechnungen:{title:'Rechnungen',kicker:'ABRECHNUNG',copy:'Zahlungsstände und Fälligkeiten zuverlässig kontrollieren.',columns:['Nummer','Kunde / Projekt','Betrag','Status'],rows:[['RE-2026-045','Bauprojekt Schmidt','2.850 €','Bezahlt'],['RE-2026-044','Müller Innenausbau','4.120 €','Teilweise bezahlt'],['RE-2026-043','Architektur König','1.980 €','Bezahlt'],['RE-2026-042','Privatkunde Wagner','3.450 €','Überfällig']]},
  kunden:{title:'Kunden',kicker:'KUNDENVERWALTUNG',copy:'Kontakte, Vorgänge und die gesamte Historie an einem Ort.',columns:['Kürzel','Unternehmen','Ansprechpartner','Status'],rows:[['MM','Müller Innenausbau','Max Müller','3 Vorgänge'],['AK','Architektur König','Anna König','1 Angebot'],['WL','Wohnbau Lange','Stefan Lange','Aktiv'],['PW','Privatkunde Wagner','Petra Wagner','Rechnung offen']]}
};

function LineChart(){return <div className="dash-chart"><div className="dash-gridlines"/><svg viewBox="0 0 700 240" role="img" aria-label="Einnahmen und Ausgaben im Jahresverlauf"><path className="dash-area" d="M0 190 C65 185 85 145 140 150 S230 105 290 125 S380 72 440 98 S545 58 600 70 S665 35 700 43 L700 240 L0 240Z"/><path className="dash-line" d="M0 190 C65 185 85 145 140 150 S230 105 290 125 S380 72 440 98 S545 58 600 70 S665 35 700 43"/><path className="dash-line expense" d="M0 208 C90 207 100 185 170 192 S280 168 350 184 S470 166 535 187 S630 161 700 169"/></svg><div className="dash-months"><span>Jan</span><span>Mär</span><span>Mai</span><span>Jul</span><span>Sep</span><span>Nov</span></div></div>}

function Dashboard(){return <>
  <div className="dash-metrics four"><article><small>Offene Aufträge</small><strong>18</strong><em>Gesamtwert: 157.430 €</em></article><article><small>Lagerwert</small><strong>86.250 €</strong><em>152 Positionen</em></article><article><small>Offene Angebote</small><strong>11</strong><em>Gesamtwert: 68.540 €</em></article><article><small>Offene Rechnungen</small><strong>9</strong><em>Gesamtwert: 34.280 €</em></article></div>
  <div className="dash-overview-grid wide"><article className="dash-chart-card"><div className="dash-card-head"><div><small>GESCHÄFTSENTWICKLUNG</small><h4>Einnahmen vs. Ausgaben</h4></div><button type="button">Dieses Jahr⌄</button></div><div className="chart-legend"><span><i/>Einnahmen</span><span><i/>Ausgaben</span></div><LineChart/></article><article className="dash-invoices"><div className="dash-card-head"><h4>Letzte Rechnungen</h4><button type="button">Alle anzeigen</button></div>{[['RE-2026-045','Bauprojekt Schmidt','2.850 €','Bezahlt'],['RE-2026-044','Müller Innenausbau','4.120 €','Teilbezahlt'],['RE-2026-043','Architektur König','1.980 €','Bezahlt'],['RE-2026-042','Privatkunde Wagner','3.450 €','Überfällig']].map((r,i)=><div className="invoice-row" key={r[0]}><small>{r[0]}</small><strong>{r[1]}</strong><span>{r[2]}</span><em className={`mini-status s-${i}`}>{r[3]}</em></div>)}</article></div>
  <div className="dash-bottom-grid"><article><div className="dash-card-head"><h4>Niedriger Materialbestand</h4><button type="button">Alle</button></div>{[['Zement 25kg','12 Sack'],['Holzlatten 4×6cm','18 Stück'],['Dämmwolle 10cm','5 Rollen']].map(x=><div className="compact-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><em>Unter Mindestbestand</em></div>)}</article><article><div className="dash-card-head"><h4>Angebote in Bearbeitung</h4><button type="button">Alle</button></div>{[['ANG-028','Neubau Müller','18.750 €'],['ANG-027','Sanierung Schule','12.340 €'],['ANG-026','Anbau Weber','8.950 €']].map(x=><div className="compact-row" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><em>{x[2]}</em></div>)}</article><article><div className="dash-card-head"><h4>Aktive Aufträge</h4><button type="button">Alle</button></div>{[['Neubau Einfamilienhaus','65%'],['Sanierung Altbau','40%'],['Dachgeschossausbau','80%']].map(x=><div className="progress-row" key={x[0]}><b>{x[0]}</b><i><em style={{width:x[1]}}/></i><span>{x[1]}</span></div>)}</article></div>
  </>}

function TableView({kind}:{kind:'auftraege'|'material'|'angebote'|'rechnungen'|'kunden'}){const view=data[kind];return <div className="dash-list-view"><div className="dash-view-head"><div><small>{view.kicker}</small><h3>{view.title}</h3><p>{view.copy}</p></div><button type="button">+ Neu anlegen</button></div><div className="dash-table"><div className="dash-table-row dash-table-head">{view.columns.map(x=><span key={x}>{x}</span>)}</div>{view.rows.map((row,index)=><div className="dash-table-row" key={row[0]}>{row.map((cell,i)=><span key={cell} className={i===3?`status status-${index}`:''}>{i===0&&kind==='kunden'?<b className="customer-avatar">{cell}</b>:cell}</span>)}</div>)}</div></div>}

function FinanceView(){return <div><div className="dash-view-head"><div><small>EINNAHMEN & AUSGABEN</small><h3>Finanzübersicht</h3><p>Geschäftsentwicklung und Ergebnis jederzeit verstehen.</p></div><button type="button">+ Buchung</button></div><div className="finance-kpis"><article><small>Einnahmen</small><strong>86.250 €</strong><span>+14,2 %</span></article><article><small>Ausgaben</small><strong>31.480 €</strong><span className="neutral">+3,1 %</span></article><article><small>Ergebnis</small><strong>54.770 €</strong><span>+21,8 %</span></article></div><article className="finance-chart"><div className="dash-card-head"><div><small>MONATSVERLAUF</small><h4>Einnahmen vs. Ausgaben</h4></div></div><LineChart/></article></div>}

function ReportsView(){return <div><div className="dash-view-head"><div><small>BERICHTE</small><h3>Unternehmenskennzahlen</h3><p>Die wichtigsten Entwicklungen kompakt ausgewertet.</p></div><button type="button">PDF exportieren</button></div><div className="report-grid">{[['Umsatzentwicklung','+14,2%','gegenüber Vorjahr'],['Angebotsquote','62%','7 von 11 angenommen'],['Ø Zahlungsdauer','12 Tage','2 Tage schneller'],['Materialumschlag','4,8×','im laufenden Jahr']].map(x=><article key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></article>)}</div><article className="finance-chart"><div className="dash-card-head"><h4>Entwicklung der letzten 12 Monate</h4></div><LineChart/></article></div>}

function SettingsView(){return <div><div className="dash-view-head"><div><small>EINSTELLUNGEN</small><h3>Unternehmen konfigurieren</h3><p>Firmendaten, Nutzer und Dokumenteinstellungen verwalten.</p></div></div><div className="settings-grid">{[['Firmendaten','Musterbau GmbH','Adresse, Steuerdaten und Bankverbindung'],['Nutzer & Rollen','5 aktive Nutzer','Zugriffe und Verantwortlichkeiten'],['Nummernkreise','2026 fortlaufend','Angebote, Aufträge und Rechnungen'],['Dokumentvorlagen','Standardvorlage','Logo, Farben und Zahlungsbedingungen']].map(x=><button type="button" key={x[0]}><span><strong>{x[0]}</strong><small>{x[2]}</small></span><em>{x[1]}</em></button>)}</div></div>}

export function ProductMap(){const[active,setActive]=useState<ViewId>('dashboard');const current=navigation.find(x=>x[0]===active)?.[1]??'Dashboard';return <div className="interactive-dashboard detailed"><aside className="dash-sidebar"><div className="dash-logo"><span className="mini-brand-mark"><i/><i/></span><b>VYSN</b></div><div className="dash-nav" aria-label="Interaktive VYSN One Navigation">{navigation.map(([id,label,Icon])=><button type="button" key={id} className={active===id?'active':''} onClick={()=>setActive(id)} aria-pressed={active===id}><Icon/><span>{label}</span></button>)}</div><div className="dash-plan"><strong>✦ VYSN ONE</strong><small>Dein aktueller Plan</small></div></aside><section className="dash-main" aria-live="polite"><div className="dash-top"><div><small>DIENSTAG, 1. SEPTEMBER · {current.toUpperCase()}</small><h2>{active==='dashboard'?'Guten Morgen, Max. 👋':current}</h2></div><div className="dash-user"><i>⌕</i><span>MM</span></div></div>{active==='dashboard'?<Dashboard/>:active==='finanzen'?<FinanceView/>:active==='berichte'?<ReportsView/>:active==='einstellungen'?<SettingsView/>:<TableView kind={active}/>}</section></div>}
