import type { Metadata } from 'next';
import { ArrowRight, Check, Clock3, Mail, MessageSquareText } from 'lucide-react';
import { SiteFooter } from '../../components/site-footer';
import { SiteHeader } from '../../components/site-header';

export const metadata: Metadata = { title:'Kontakt & Demo | VYSN One', description:'Persönliche VYSN One Demo für dein Unternehmen anfragen.' };

export default function ContactPage(){return <main><SiteHeader/>
  <section className="contact-section shell"><div className="contact-copy"><span className="section-kicker">KONTAKT & DEMO</span><h1>Lass uns deinen Betrieb<br/><span>klarer organisieren.</span></h1><p>In einer persönlichen Demo zeigen wir dir VYSN One anhand typischer Abläufe deines Unternehmens. Unverbindlich, verständlich und ohne Verkaufsdruck.</p><div className="contact-benefits">{['30 Minuten persönliche Produktdemo','Fragen zu Funktionen und Einführung','Klare Einschätzung, ob VYSN One passt'].map(x=><span key={x}><Check/>{x}</span>)}</div><div className="contact-direct"><div><Mail/><span><small>E-Mail</small><a href="mailto:hallo@vysn.de">hallo@vysn.de</a></span></div><div><Clock3/><span><small>Antwortzeit</small><strong>In der Regel innerhalb eines Werktags</strong></span></div></div></div>
  <div className="contact-card"><div className="contact-card-head"><MessageSquareText/><div><span>DEMO ANFRAGEN</span><h2>Erzähl uns kurz von deinem Unternehmen.</h2></div></div><form action="mailto:hallo@vysn.de" method="post" encType="text/plain"><label>Vor- und Nachname<input name="Name" required placeholder="Max Mustermann"/></label><label>Unternehmen<input name="Unternehmen" required placeholder="Musterbau GmbH"/></label><div className="form-row"><label>E-Mail<input name="E-Mail" type="email" required placeholder="max@unternehmen.de"/></label><label>Teamgröße<select name="Teamgröße" defaultValue=""><option value="" disabled>Bitte wählen</option><option>1–2 Personen</option><option>3–5 Personen</option><option>6–10 Personen</option><option>Mehr als 10</option></select></label></div><label>Was möchtest du verbessern?<textarea name="Nachricht" rows={5} placeholder="Zum Beispiel: Aufträge und Rechnungen besser verbinden …"/></label><label className="consent"><input type="checkbox" required/><span>Ich bin damit einverstanden, zur Bearbeitung meiner Anfrage kontaktiert zu werden.</span></label><button className="button button-primary" type="submit">Demo anfragen <ArrowRight/></button><small>Beim Absenden öffnet sich dein E-Mail-Programm mit den eingetragenen Angaben.</small></form></div></section><SiteFooter/></main>}
