import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Check, DatabaseBackup, Eye, KeyRound, LockKeyhole, Server, ShieldCheck, UserCheck, type LucideIcon } from 'lucide-react';
import { SiteFooter } from '../../components/site-footer';
import { SiteHeader } from '../../components/site-header';

export const metadata: Metadata = { title:'Sicherheit | VYSN One', description:'Sicherheitsprinzipien, Zugriffsschutz, Backups und Datenschutz bei VYSN One.' };
const pillars:Array<[LucideIcon,string,string]>=[[LockKeyhole,'Geschützte Übertragung','Die Verbindung zur Anwendung wird verschlüsselt übertragen.'],[KeyRound,'Rollen & Berechtigungen','Zugriffe werden passend zu Aufgaben und Verantwortlichkeiten organisiert.'],[DatabaseBackup,'Datensicherung','Regelmäßige Sicherungen unterstützen Wiederherstellung und Betriebskontinuität.'],[Eye,'Nachvollziehbare Abläufe','Klare Status und Zuständigkeiten machen Geschäftsprozesse verständlich.'],[Server,'Kontrollierte Infrastruktur','Hosting, Betrieb und technische Abhängigkeiten werden bewusst geplant.'],[UserCheck,'Sicherer Umgang im Team','Berechtigungen und organisatorische Regeln ergänzen den technischen Schutz.']];

export default function SecurityPage(){return <main><SiteHeader/>
  <section className="security-hero"><div className="shell security-hero-inner"><div><span className="section-kicker light">SICHERHEIT BEI VYSN ONE</span><h1>Geschäftsdaten verdienen<br/><span>klare Kontrolle.</span></h1><p>VYSN One berücksichtigt Sicherheit technisch und organisatorisch – vom verschlüsselten Zugriff bis zu Rollen, Datensicherung und transparenten Verantwortlichkeiten.</p><Link className="button button-light" href="/kontakt">Sicherheit besprechen <ArrowRight/></Link></div><div className="security-orbit"><div className="orbit-ring one"/><div className="orbit-ring two"/><div className="shield-center"><ShieldCheck/></div><span className="security-tag tag-1">Zugriff <Check/></span><span className="security-tag tag-2">Backups <Check/></span><span className="security-tag tag-3">Rollen <Check/></span></div></div></section>
  <section className="detail-section shell"><div className="section-heading"><div><span className="section-kicker">SCHUTZ AUF MEHREREN EBENEN</span><h2>Ein Zusammenspiel, kein einzelner Schalter.</h2></div><p>Wir betrachten Anwendung, Infrastruktur und Nutzung gemeinsam, weil wirksame Sicherheit mehrere Ebenen braucht.</p></div><div className="security-grid">{pillars.map(([Icon,title,text])=><article key={String(title)}><div><Icon/></div><h3>{String(title)}</h3><p>{String(text)}</p></article>)}</div></section>
  <section className="responsibility-section"><div className="shell responsibility-grid"><div><span className="section-kicker">DATENSCHUTZ & VERANTWORTUNG</span><h2>Für einen bewussten Umgang mit Unternehmensdaten.</h2><p>VYSN One soll Unternehmen dabei unterstützen, Datenflüsse und Zugriffe strukturiert zu organisieren. Konkrete technische und organisatorische Maßnahmen sowie Auftragsverarbeitung werden vor Vertragsschluss transparent dokumentiert.</p></div><div className="responsibility-card"><h3>Unsere Grundprinzipien</h3>{['Nur notwendige Zugriffe','Klare Nutzerrollen','Kontrollierte Konfiguration','Planbare Datensicherung','Transparente Dokumentation'].map(x=><span key={x}><Check/>{x}</span>)}</div></div></section>
  <section className="security-note shell"><ShieldCheck/><div><h2>Keine leeren Sicherheitsversprechen.</h2><p>Verbindliche Angaben zu Hostingstandort, Verfügbarkeit, Aufbewahrung und Datenschutz werden in den jeweils gültigen Vertrags- und Datenschutzunterlagen festgehalten.</p></div></section>
  <section className="home-cta shell"><div><span className="section-kicker light">NOCH FRAGEN?</span><h2>Wir erklären die Sicherheitsarchitektur verständlich.</h2></div><Link className="button button-light" href="/kontakt">Gespräch vereinbaren <ArrowRight/></Link></section><SiteFooter/></main>}
