import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Check, DatabaseBackup, Eye, KeyRound, LockKeyhole, Server, ShieldCheck } from 'lucide-react';
import { SiteFooter } from '../../components/site-footer';
import { SiteHeader } from '../../components/site-header';

export const metadata: Metadata = { title: 'Sicherheit | VYSN', description: 'Wie VYSN Unternehmensdaten mit Rollen, Verschlüsselung und kontrollierten Prozessen schützt.' };
const pillars=[[LockKeyhole,'Verschlüsselte Übertragung','Daten werden bei der Übertragung über moderne TLS-Verbindungen geschützt.'],[KeyRound,'Rollen & Rechte','Nutzer sehen und bearbeiten nur die Bereiche, die sie für ihre Arbeit benötigen.'],[DatabaseBackup,'Backups','Regelmäßige Sicherungen unterstützen Wiederherstellung und Betriebskontinuität.'],[Eye,'Nachvollziehbarkeit','Änderungen und Freigaben können in klaren Prozessketten dokumentiert werden.'],[Server,'Europäisches Hosting','Hosting und Datenverarbeitung in Europa sind für den Betrieb planbar.'],[ShieldCheck,'Datenschutz im Design','VYSN wird mit datensparsamen, kontrollierbaren Abläufen konzipiert.']];

export default function SecurityPage(){return <main><SiteHeader />
  <section className="security-hero"><div className="shell security-hero-inner"><div><span className="section-kicker light">SICHERHEIT</span><h1>Deine Daten.<br/><span>Deine Kontrolle.</span></h1><p>VYSN schafft eine sichere Basis für professionelles Arbeiten – mit klaren Zugriffsrechten, moderner Verschlüsselung und nachvollziehbaren Prozessen.</p><Link className="button button-light" href="/preise">VYSN kennenlernen <ArrowRight/></Link></div><div className="security-orbit"><div className="orbit-ring one"/><div className="orbit-ring two"/><div className="shield-center"><ShieldCheck/></div><span className="security-tag tag-1">TLS <Check/></span><span className="security-tag tag-2">Backups <Check/></span><span className="security-tag tag-3">Rollen <Check/></span></div></div></section>
  <section className="detail-section shell"><div className="section-heading"><div><span className="section-kicker">SCHUTZ AUF MEHREREN EBENEN</span><h2>Sicherheit ist Teil des Systems.</h2></div><p>Nicht nur eine einzelne Funktion, sondern ein Zusammenspiel aus Technik, Berechtigungen und klaren Abläufen.</p></div><div className="security-grid">{pillars.map(([Icon,title,text])=><article key={String(title)}><div><Icon/></div><h3>{String(title)}</h3><p>{String(text)}</p></article>)}</div></section>
  <section className="responsibility-section"><div className="shell responsibility-grid"><div><span className="section-kicker">DATENSCHUTZ</span><h2>Für verantwortungsvolle Datenverarbeitung.</h2><p>VYSN unterstützt Unternehmen dabei, Zugriffe und Datenflüsse nachvollziehbar zu organisieren. Konkrete technische und organisatorische Maßnahmen werden passend zur gewählten Version und Hosting-Konfiguration dokumentiert.</p></div><div className="responsibility-card"><h3>VYSN Sicherheitsprinzipien</h3>{['So wenig Zugriff wie nötig','Klare Zuständigkeiten','Kontrollierte Freigaben','Planbare Datensicherung','Transparente Konfiguration'].map(x=><span key={x}><Check/>{x}</span>)}</div></div></section>
  <section className="home-cta shell"><div><span className="section-kicker light">VYSN PRO</span><h2>Besondere Sicherheits- oder Compliance-Anforderungen?</h2></div><a className="button button-light" href="mailto:hallo@vysn.de?subject=VYSN%20Sicherheitsanforderungen">Anforderungen besprechen <ArrowRight/></a></section>
  <SiteFooter /></main>}
